services:
  bot:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: python bot.py

  website:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: python app.py
